version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin $ECR_REGISTRY
      - echo Getting the code version...
      - export CODE_VERSION=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t Lab2-php-container:${CODE_VERSION} .
      - docker tag Lab2-php-container:${CODE_VERSION} $ECR_REGISTRY/$ECR_REPOSITORY:${CODE_VERSION}
      - docker tag Lab2-php-container:${CODE_VERSION} $ECR_REGISTRY/$ECR_REPOSITORY:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $ECR_REGISTRY/$ECR_REPOSITORY:${CODE_VERSION}
      - docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
      - echo Writing image definition file for ECS deployment...
      - printf '[{"name":"Lab2-php-container","imageUri":"%s"}]' $ECR_REGISTRY/$ECR_REPOSITORY:${CODE_VERSION} > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
